name: Docker Image CI

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*.*.*'

jobs:

  buildAndPush:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lorenzoscebba/azure-boards-pbi-autorule:latest,lorenzoscebba/azure-boards-pbi-autorule:${{ env.RELEASE_VERSION }}
